name: "Exercise 1: Print Name With Manual Trigger"

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        default: "Name"

jobs:
  print-name:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputted name
        run: echo ${{ inputs.name }}
