name: "Exercise 2: Run on main only"

on:
  push:

jobs:
  print-branch:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Print inputted name
        run: echo "Running job on branch ${{ github.ref }}"
